version: 0.1
environment_variables:
    plaintext:
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
			- npm uninstall --save-dev angular-cli
			- npm install --save-dev @angular/cli@latest
			- npm install -g @angular/cli@latest
    build:
        commands:
            - echo Build started on `date`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
